# Neural Network

# Q2-GasTurbines
predicting turbine energy yield (TEY) using ambient variables as features.

In [1]:
import numpy as np
import pandas as pd

In [2]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV, KFold
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.optimizers import Adam
from keras.layers import Dropout

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
df=pd.read_csv("/content/gas_turbines.csv")
df

,AT,AP,AH,AFDP,GTEP,TIT,TAT,TEY,CDP,CO,NOX
0,6.8594,1007.9,96.799,3.5000,19.663,1059.2,550.00,114.70,10.605,3.1547,82.722
1,6.7850,1008.4,97.118,3.4998,19.728,1059.3,550.00,114.72,10.598,3.2363,82.776
2,6.8977,1008.8,95.939,3.4824,19.779,1059.4,549.87,114.71,10.601,3.2012,82.468
3,7.0569,1009.2,95.249,3.4805,19.792,1059.6,549.99,114.72,10.606,3.1923,82.670
4,7.3978,1009.7,95.150,3.4976,19.765,1059.7,549.98,114.72,10.612,3.2484,82.311
...,...,...,...,...,...,...,...,...,...,...,...
15034,9.0301,1005.6,98.460,3.5421,19.164,1049.7,546.21,111.61,10.400,4.5186,79.559
15035,7.8879,1005.9,99.093,3.5059,19.414,1046.3,543.22,111.78,10.433,4.8470,79.917
15036,7.2647,1006.3,99.496,3.4770,19.530,1037.7,537.32,110.19,10.483,7.9632,90.912
15037,7.0060,1006.8,99.008,3.4486,19.377,1043.2,541.24,110.74,10.533,6.2494,93.227
15038,6.9279,1007.2,97.533,3.4275,19.306,1049.9,545.85,111.58,10.583,4.9816,92.498

# EDA

In [5]:
df= df.drop(['AFDP','GTEP','TIT','TAT','CDP','CO','NOX'],axis=1)
df.head()

       AT      AP      AH     TEY
0  6.8594  1007.9  96.799  114.70
1  6.7850  1008.4  97.118  114.72
2  6.8977  1008.8  95.939  114.71
3  7.0569  1009.2  95.249  114.72
4  7.3978  1009.7  95.150  114.72

In [6]:
df.shape

(15039, 4)

In [7]:
df.describe()

                 AT           AP            AH           TEY
count  15039.000000  15039.00000  15039.000000  15039.000000
mean      17.764381   1013.19924     79.124174    134.188464
std        7.574323      6.41076     13.793439     15.829717
min        0.522300    985.85000     30.344000    100.170000
25%       11.408000   1008.90000     69.750000    127.985000
50%       18.186000   1012.80000     82.266000    133.780000
75%       23.862500   1016.90000     90.043500    140.895000
max       34.929000   1034.20000    100.200000    174.610000

In [8]:
df.isnull().sum()

AT     0
AP     0
AH     0
TEY    0
dtype: int64

In [9]:
x=df.iloc[:,1:5]
y=df.iloc[:,0]

In [10]:
x

           AP      AH     TEY
0      1007.9  96.799  114.70
1      1008.4  97.118  114.72
2      1008.8  95.939  114.71
3      1009.2  95.249  114.72
4      1009.7  95.150  114.72
...       ...     ...     ...
15034  1005.6  98.460  111.61
15035  1005.9  99.093  111.78
15036  1006.3  99.496  110.19
15037  1006.8  99.008  110.74
15038  1007.2  97.533  111.58

[15039 rows x 3 columns]

In [11]:
y

0        6.8594
1        6.7850
2        6.8977
3        7.0569
4        7.3978
          ...
15034    9.0301
15035    7.8879
15036    7.2647
15037    7.0060
15038    6.9279
Name: AT, Length: 15039, dtype: float64

# Model Building

In [12]:
model = Sequential()
model.add(Dense(12, input_dim=3,  kernel_initializer='uniform', activation='relu'))
model.add(Dense(8,  kernel_initializer='uniform', activation='relu'))
model.add(Dense(1,  kernel_initializer='uniform', activation='sigmoid'))

In [13]:
model.compile(optimizer='adam', loss='mse', metrics=['mse'])

In [14]:
history= model.fit(x, y,validation_split=0.33, epochs=150, batch_size=10)

Epoch 1/150
1008/1008 [==============================] - 4s 3ms/step - loss: 299.6477 - mse: 299.6477 - val_loss: 417.7653 - val_mse: 417.7653
Epoch 2/150
1008/1008 [==============================] - 4s 3ms/step - loss: 299.3252 - mse: 299.3252 - val_loss: 417.7647 - val_mse: 417.7647
Epoch 3/150
1008/1008 [==============================] - 4s 4ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7646 - val_mse: 417.7646
Epoch 4/150
1008/1008 [==============================] - 4s 4ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 5/150
1008/1008 [==============================] - 3s 3ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 6/150
1008/1008 [==============================] - 4s 4ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 7/150
1008/1008 [==============================] - 4s 4ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 8/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 9/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3248 - mse: 299.3248 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 10/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 11/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 12/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 13/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 14/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 15/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 16/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3253 - mse: 299.3253 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 17/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3252 - mse: 299.3252 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 18/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3248 - mse: 299.3248 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 19/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 20/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 21/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 22/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 23/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 24/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 25/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3248 - mse: 299.3248 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 26/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 27/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 28/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 29/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3252 - mse: 299.3252 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 30/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 31/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3247 - mse: 299.3247 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 32/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 33/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3248 - mse: 299.3248 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 34/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 35/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3252 - mse: 299.3252 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 36/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 37/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 38/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 39/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 40/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 41/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 42/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 43/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 44/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 45/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 46/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 47/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 48/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 49/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 50/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3248 - mse: 299.3248 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 51/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 52/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 53/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 54/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3252 - mse: 299.3252 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 55/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 56/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 57/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 58/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3248 - mse: 299.3248 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 59/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 60/150
1008/1008 [==============================] - 3s 3ms/step - loss: 299.3248 - mse: 299.3248 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 61/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 62/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3248 - mse: 299.3248 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 63/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 64/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 65/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 66/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 67/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3248 - mse: 299.3248 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 68/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 69/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 70/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 71/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 72/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3248 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 73/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 74/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3252 - mse: 299.3252 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 75/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 76/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3247 - mse: 299.3247 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 77/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 78/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 79/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 80/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3252 - mse: 299.3252 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 81/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 82/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 83/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3253 - mse: 299.3253 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 84/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3252 - mse: 299.3252 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 85/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 86/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3252 - mse: 299.3252 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 87/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 88/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3248 - mse: 299.3248 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 89/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3252 - mse: 299.3252 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 90/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 91/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 92/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 93/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 94/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 95/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 96/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 97/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 98/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 99/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3253 - mse: 299.3253 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 100/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 101/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 102/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3252 - mse: 299.3252 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 103/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 104/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3252 - mse: 299.3252 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 105/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3247 - mse: 299.3247 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 106/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 107/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3252 - mse: 299.3252 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 108/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 109/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 110/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 111/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 112/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 113/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 114/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3247 - mse: 299.3247 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 115/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3252 - mse: 299.3252 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 116/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 117/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 118/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 119/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3248 - mse: 299.3248 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 120/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 121/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 122/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3253 - mse: 299.3253 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 123/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3252 - mse: 299.3252 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 124/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 125/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 126/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 127/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3253 - mse: 299.3253 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 128/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 129/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 130/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3249 - mse: 299.3249 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 131/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 132/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 133/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 134/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 135/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 136/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3250 - mse: 299.3250 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 137/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 138/150
1008/1008 [==============================] - 2s 2ms/step - loss: 299.3251 - mse: 299.3251 - val_loss: 417.7645 - val_mse: 417.7645
Epoch 139/150

In [15]:
scores = model.evaluate(x, y)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

470/470 [==============================] - 0s 993us/step - loss: 338.4111 - mse: 338.4111
mse: 33841.11%

In [16]:
history.history.keys()

dict_keys(['loss', 'mse', 'val_loss', 'val_mse'])

In [18]:
a = StandardScaler()
a.fit(x)
X_standardized = a.transform(x)

In [19]:
pd.DataFrame(X_standardized).describe()

                  0             1             2
count  1.503900e+04  1.503900e+04  1.503900e+04
mean  -1.875504e-14  2.570219e-16  1.081004e-15
std    1.000033e+00  1.000033e+00  1.000033e+00
min   -4.266288e+00 -3.536594e+00 -2.149097e+00
25%   -6.706510e-01 -6.796337e-01 -3.919003e-01
50%   -6.227861e-02  2.277844e-01 -2.580448e-02
75%    5.772924e-01  7.916582e-01  4.236815e-01
max    3.275970e+00  1.528011e+00  2.553607e+00

In [20]:
def create_model():
    model = Sequential()
    model.add(Dense(12, input_dim=3, kernel_initializer='uniform', activation='relu'))
    model.add(Dense(8, kernel_initializer='uniform', activation='relu'))
    model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))\
    
    adam=Adam(lr=0.01)
    model.compile(loss='mse', optimizer=adam, metrics=['mse'])
    return model

In [21]:
model = KerasClassifier(build_fn = create_model,verbose = 0)
# Define the grid search parameters
batch_size = [10,20,40]
epochs = [10,50,100]
# Make a dictionary of the grid search parameters
param_grid = dict(batch_size = batch_size,epochs = epochs)
# Build and fit the GridSearchCV
grid = GridSearchCV(estimator = model,param_grid = param_grid,cv = KFold(),verbose = 10)
grid_result = grid.fit(X_standardized,y)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV 1/5; 1/9] START batch_size=10, epochs=10....................................
[CV 1/5; 1/9] END .......batch_size=10, epochs=10;, score=nan total time=  21.4s
[CV 2/5; 1/9] START batch_size=10, epochs=10....................................
[CV 2/5; 1/9] END .......batch_size=10, epochs=10;, score=nan total time=  21.3s
[CV 3/5; 1/9] START batch_size=10, epochs=10....................................
[CV 3/5; 1/9] END .......batch_size=10, epochs=10;, score=nan total time=  21.4s
[CV 4/5; 1/9] START batch_size=10, epochs=10....................................
[CV 4/5; 1/9] END .......batch_size=10, epochs=10;, score=nan total time=  21.7s
[CV 5/5; 1/9] START batch_size=10, epochs=10....................................
[CV 5/5; 1/9] END .......batch_size=10, epochs=10;, score=nan total time=  21.4s
[CV 1/5; 2/9] START batch_size=10, epochs=50....................................
[CV 1/5; 2/9] END .......batch_size=10, epochs=50;, score=nan total time=  54.7s
[CV 2/5; 2/9] START batch_size=10, epochs=50....................................
[CV 2/5; 2/9] END .......batch_size=10, epochs=50;, score=nan total time= 1.4min
[CV 3/5; 2/9] START batch_size=10, epochs=50....................................
[CV 3/5; 2/9] END .......batch_size=10, epochs=50;, score=nan total time=  54.2s
[CV 4/5; 2/9] START batch_size=10, epochs=50....................................
[CV 4/5; 2/9] END .......batch_size=10, epochs=50;, score=nan total time= 1.4min
[CV 5/5; 2/9] START batch_size=10, epochs=50....................................
[CV 5/5; 2/9] END .......batch_size=10, epochs=50;, score=nan total time= 1.4min
[CV 1/5; 3/9] START batch_size=10, epochs=100...................................
[CV 1/5; 3/9] END ......batch_size=10, epochs=100;, score=nan total time= 2.4min
[CV 2/5; 3/9] START batch_size=10, epochs=100...................................
[CV 2/5; 3/9] END ......batch_size=10, epochs=100;, score=nan total time= 1.9min
[CV 3/5; 3/9] START batch_size=10, epochs=100...................................
[CV 3/5; 3/9] END ......batch_size=10, epochs=100;, score=nan total time= 1.9min
[CV 4/5; 3/9] START batch_size=10, epochs=100...................................
[CV 4/5; 3/9] END ......batch_size=10, epochs=100;, score=nan total time= 2.4min
[CV 5/5; 3/9] START batch_size=10, epochs=100...................................
[CV 5/5; 3/9] END ......batch_size=10, epochs=100;, score=nan total time= 2.4min
[CV 1/5; 4/9] START batch_size=20, epochs=10....................................
[CV 1/5; 4/9] END .......batch_size=20, epochs=10;, score=nan total time=  10.9s
[CV 2/5; 4/9] START batch_size=20, epochs=10....................................
[CV 2/5; 4/9] END .......batch_size=20, epochs=10;, score=nan total time=   6.6s
[CV 3/5; 4/9] START batch_size=20, epochs=10....................................
[CV 3/5; 4/9] END .......batch_size=20, epochs=10;, score=nan total time=  10.9s
[CV 4/5; 4/9] START batch_size=20, epochs=10....................................
[CV 4/5; 4/9] END .......batch_size=20, epochs=10;, score=nan total time=  10.9s
[CV 5/5; 4/9] START batch_size=20, epochs=10....................................
[CV 5/5; 4/9] END .......batch_size=20, epochs=10;, score=nan total time=  11.5s
[CV 1/5; 5/9] START batch_size=20, epochs=50....................................
[CV 1/5; 5/9] END .......batch_size=20, epochs=50;, score=nan total time=  41.7s
[CV 2/5; 5/9] START batch_size=20, epochs=50....................................
[CV 2/5; 5/9] END .......batch_size=20, epochs=50;, score=nan total time=  41.7s
[CV 3/5; 5/9] START batch_size=20, epochs=50....................................
[CV 3/5; 5/9] END .......batch_size=20, epochs=50;, score=nan total time=  41.6s
[CV 4/5; 5/9] START batch_size=20, epochs=50....................................
[CV 4/5; 5/9] END .......batch_size=20, epochs=50;, score=nan total time=  41.7s
[CV 5/5; 5/9] START batch_size=20, epochs=50....................................
[CV 5/5; 5/9] END .......batch_size=20, epochs=50;, score=nan total time=  41.7s
[CV 1/5; 6/9] START batch_size=20, epochs=100...................................
[CV 1/5; 6/9] END ......batch_size=20, epochs=100;, score=nan total time= 1.4min
[CV 2/5; 6/9] START batch_size=20, epochs=100...................................
[CV 2/5; 6/9] END ......batch_size=20, epochs=100;, score=nan total time= 1.4min
[CV 3/5; 6/9] START batch_size=20, epochs=100...................................
[CV 3/5; 6/9] END ......batch_size=20, epochs=100;, score=nan total time= 1.4min
[CV 4/5; 6/9] START batch_size=20, epochs=100...................................
[CV 4/5; 6/9] END ......batch_size=20, epochs=100;, score=nan total time=  57.4s
[CV 5/5; 6/9] START batch_size=20, epochs=100...................................
[CV 5/5; 6/9] END ......batch_size=20, epochs=100;, score=nan total time= 1.4min
[CV 1/5; 7/9] START batch_size=40, epochs=10....................................
[CV 1/5; 7/9] END .......batch_size=40, epochs=10;, score=nan total time=   3.8s
[CV 2/5; 7/9] START batch_size=40, epochs=10....................................
[CV 2/5; 7/9] END .......batch_size=40, epochs=10;, score=nan total time=   5.7s
[CV 3/5; 7/9] START batch_size=40, epochs=10....................................
[CV 3/5; 7/9] END .......batch_size=40, epochs=10;, score=nan total time=   3.4s
[CV 4/5; 7/9] START batch_size=40, epochs=10....................................
[CV 4/5; 7/9] END .......batch_size=40, epochs=10;, score=nan total time=   5.7s
[CV 5/5; 7/9] START batch_size=40, epochs=10....................................
[CV 5/5; 7/9] END .......batch_size=40, epochs=10;, score=nan total time=   3.4s
[CV 1/5; 8/9] START batch_size=40, epochs=50....................................
[CV 1/5; 8/9] END .......batch_size=40, epochs=50;, score=nan total time=  14.7s
[CV 2/5; 8/9] START batch_size=40, epochs=50....................................
[CV 2/5; 8/9] END .......batch_size=40, epochs=50;, score=nan total time=  14.9s
[CV 3/5; 8/9] START batch_size=40, epochs=50....................................
[CV 3/5; 8/9] END .......batch_size=40, epochs=50;, score=nan total time=  22.0s
[CV 4/5; 8/9] START batch_size=40, epochs=50....................................
[CV 4/5; 8/9] END .......batch_size=40, epochs=50;, score=nan total time=  21.3s
[CV 5/5; 8/9] START batch_size=40, epochs=50....................................
[CV 5/5; 8/9] END .......batch_size=40, epochs=50;, score=nan total time=  15.6s
[CV 1/5; 9/9] START batch_size=40, epochs=100...................................
[CV 1/5; 9/9] END ......batch_size=40, epochs=100;, score=nan total time=  29.0s
[CV 2/5; 9/9] START batch_size=40, epochs=100...................................
[CV 2/5; 9/9] END ......batch_size=40, epochs=100;, score=nan total time=  41.6s
[CV 3/5; 9/9] START batch_size=40, epochs=100...................................
[CV 3/5; 9/9] END ......batch_size=40, epochs=100;, score=nan total time=  41.6s
[CV 4/5; 9/9] START batch_size=40, epochs=100...................................
[CV 4/5; 9/9] END ......batch_size=40, epochs=100;, score=nan total time=  29.2s
[CV 5/5; 9/9] START batch_size=40, epochs=100...................................
[CV 5/5; 9/9] END ......batch_size=40, epochs=100;, score=nan total time=  41.6s

In [22]:
print('Best : {}, using {}'.format(grid_result.best_score_,grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
  print('{},{} with: {}'.format(mean, stdev, param))

Best : nan, using {'batch_size': 10, 'epochs': 10}
nan,nan with: {'batch_size': 10, 'epochs': 10}
nan,nan with: {'batch_size': 10, 'epochs': 50}
nan,nan with: {'batch_size': 10, 'epochs': 100}
nan,nan with: {'batch_size': 20, 'epochs': 10}
nan,nan with: {'batch_size': 20, 'epochs': 50}
nan,nan with: {'batch_size': 20, 'epochs': 100}
nan,nan with: {'batch_size': 40, 'epochs': 10}
nan,nan with: {'batch_size': 40, 'epochs': 50}
nan,nan with: {'batch_size': 40, 'epochs': 100}

In [23]:
def create_model(learning_rate,dropout_rate):
    model = Sequential()
    model.add(Dense(8,input_dim = 3,kernel_initializer = 'normal',activation = 'relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(4,input_dim = 3,kernel_initializer = 'normal',activation = 'relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(1,activation = 'sigmoid'))
    
    adam = Adam(lr = learning_rate)
    model.compile(loss = 'mse',optimizer = adam,metrics = ['mse'])
    return model

In [24]:
model = KerasClassifier(build_fn = create_model,verbose = 0,batch_size = 40,epochs = 10)

# Define the grid search parameters

learning_rate = [0.001,0.01,0.1]
dropout_rate = [0.0,0.1,0.2]

# Make a dictionary of the grid search parameters

param_grids = dict(learning_rate = learning_rate,dropout_rate = dropout_rate)

# Build and fit the GridSearchCV

grid = GridSearchCV(estimator = model,param_grid = param_grids,cv = KFold(),verbose = 10)
grid_result = grid.fit(X_standardized,y)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV 1/5; 1/9] START dropout_rate=0.0, learning_rate=0.001.......................
[CV 1/5; 1/9] END dropout_rate=0.0, learning_rate=0.001;, score=nan total time=   3.9s
[CV 2/5; 1/9] START dropout_rate=0.0, learning_rate=0.001.......................
[CV 2/5; 1/9] END dropout_rate=0.0, learning_rate=0.001;, score=nan total time=   5.8s
[CV 3/5; 1/9] START dropout_rate=0.0, learning_rate=0.001.......................
[CV 3/5; 1/9] END dropout_rate=0.0, learning_rate=0.001;, score=nan total time=   5.8s
[CV 4/5; 1/9] START dropout_rate=0.0, learning_rate=0.001.......................
[CV 4/5; 1/9] END dropout_rate=0.0, learning_rate=0.001;, score=nan total time=   3.5s
[CV 5/5; 1/9] START dropout_rate=0.0, learning_rate=0.001.......................
[CV 5/5; 1/9] END dropout_rate=0.0, learning_rate=0.001;, score=nan total time=   5.8s
[CV 1/5; 2/9] START dropout_rate=0.0, learning_rate=0.01........................
[CV 1/5; 2/9] END dropout_rate=0.0, learning_rate=0.01;, score=nan total time=   5.7s
[CV 2/5; 2/9] START dropout_rate=0.0, learning_rate=0.01........................
[CV 2/5; 2/9] END dropout_rate=0.0, learning_rate=0.01;, score=nan total time=   3.5s
[CV 3/5; 2/9] START dropout_rate=0.0, learning_rate=0.01........................
[CV 3/5; 2/9] END dropout_rate=0.0, learning_rate=0.01;, score=nan total time=   5.7s
[CV 4/5; 2/9] START dropout_rate=0.0, learning_rate=0.01........................
[CV 4/5; 2/9] END dropout_rate=0.0, learning_rate=0.01;, score=nan total time=   5.8s
[CV 5/5; 2/9] START dropout_rate=0.0, learning_rate=0.01........................
[CV 5/5; 2/9] END dropout_rate=0.0, learning_rate=0.01;, score=nan total time=   6.4s
[CV 1/5; 3/9] START dropout_rate=0.0, learning_rate=0.1.........................
[CV 1/5; 3/9] END dropout_rate=0.0, learning_rate=0.1;, score=nan total time=   3.5s
[CV 2/5; 3/9] START dropout_rate=0.0, learning_rate=0.1.........................
[CV 2/5; 3/9] END dropout_rate=0.0, learning_rate=0.1;, score=nan total time=   5.8s
[CV 3/5; 3/9] START dropout_rate=0.0, learning_rate=0.1.........................
[CV 3/5; 3/9] END dropout_rate=0.0, learning_rate=0.1;, score=nan total time=   5.8s
[CV 4/5; 3/9] START dropout_rate=0.0, learning_rate=0.1.........................
[CV 4/5; 3/9] END dropout_rate=0.0, learning_rate=0.1;, score=nan total time=   3.5s
[CV 5/5; 3/9] START dropout_rate=0.0, learning_rate=0.1.........................
[CV 5/5; 3/9] END dropout_rate=0.0, learning_rate=0.1;, score=nan total time=   6.0s
[CV 1/5; 4/9] START dropout_rate=0.1, learning_rate=0.001.......................
[CV 1/5; 4/9] END dropout_rate=0.1, learning_rate=0.001;, score=nan total time=   3.6s
[CV 2/5; 4/9] START dropout_rate=0.1, learning_rate=0.001.......................
[CV 2/5; 4/9] END dropout_rate=0.1, learning_rate=0.001;, score=nan total time=   5.8s
[CV 3/5; 4/9] START dropout_rate=0.1, learning_rate=0.001.......................
[CV 3/5; 4/9] END dropout_rate=0.1, learning_rate=0.001;, score=nan total time=   3.7s
[CV 4/5; 4/9] START dropout_rate=0.1, learning_rate=0.001.......................
[CV 4/5; 4/9] END dropout_rate=0.1, learning_rate=0.001;, score=nan total time=   3.6s
[CV 5/5; 4/9] START dropout_rate=0.1, learning_rate=0.001.......................
[CV 5/5; 4/9] END dropout_rate=0.1, learning_rate=0.001;, score=nan total time=   5.8s
[CV 1/5; 5/9] START dropout_rate=0.1, learning_rate=0.01........................
[CV 1/5; 5/9] END dropout_rate=0.1, learning_rate=0.01;, score=nan total time=   3.6s
[CV 2/5; 5/9] START dropout_rate=0.1, learning_rate=0.01........................
[CV 2/5; 5/9] END dropout_rate=0.1, learning_rate=0.01;, score=nan total time=   5.8s
[CV 3/5; 5/9] START dropout_rate=0.1, learning_rate=0.01........................
[CV 3/5; 5/9] END dropout_rate=0.1, learning_rate=0.01;, score=nan total time=   3.6s
[CV 4/5; 5/9] START dropout_rate=0.1, learning_rate=0.01........................
[CV 4/5; 5/9] END dropout_rate=0.1, learning_rate=0.01;, score=nan total time=   5.9s
[CV 5/5; 5/9] START dropout_rate=0.1, learning_rate=0.01........................
[CV 5/5; 5/9] END dropout_rate=0.1, learning_rate=0.01;, score=nan total time=   5.9s
[CV 1/5; 6/9] START dropout_rate=0.1, learning_rate=0.1.........................
[CV 1/5; 6/9] END dropout_rate=0.1, learning_rate=0.1;, score=nan total time=   5.8s
[CV 2/5; 6/9] START dropout_rate=0.1, learning_rate=0.1.........................
[CV 2/5; 6/9] END dropout_rate=0.1, learning_rate=0.1;, score=nan total time=   4.5s
[CV 3/5; 6/9] START dropout_rate=0.1, learning_rate=0.1.........................
[CV 3/5; 6/9] END dropout_rate=0.1, learning_rate=0.1;, score=nan total time=   5.9s
[CV 4/5; 6/9] START dropout_rate=0.1, learning_rate=0.1.........................
[CV 4/5; 6/9] END dropout_rate=0.1, learning_rate=0.1;, score=nan total time=   3.9s
[CV 5/5; 6/9] START dropout_rate=0.1, learning_rate=0.1.........................
[CV 5/5; 6/9] END dropout_rate=0.1, learning_rate=0.1;, score=nan total time=   3.7s
[CV 1/5; 7/9] START dropout_rate=0.2, learning_rate=0.001.......................
[CV 1/5; 7/9] END dropout_rate=0.2, learning_rate=0.001;, score=nan total time=   5.8s
[CV 2/5; 7/9] START dropout_rate=0.2, learning_rate=0.001.......................
[CV 2/5; 7/9] END dropout_rate=0.2, learning_rate=0.001;, score=nan total time=   5.8s
[CV 3/5; 7/9] START dropout_rate=0.2, learning_rate=0.001.......................
[CV 3/5; 7/9] END dropout_rate=0.2, learning_rate=0.001;, score=nan total time=   4.1s
[CV 4/5; 7/9] START dropout_rate=0.2, learning_rate=0.001.......................
[CV 4/5; 7/9] END dropout_rate=0.2, learning_rate=0.001;, score=nan total time=   5.9s
[CV 5/5; 7/9] START dropout_rate=0.2, learning_rate=0.001.......................
[CV 5/5; 7/9] END dropout_rate=0.2, learning_rate=0.001;, score=nan total time=   3.7s
[CV 1/5; 8/9] START dropout_rate=0.2, learning_rate=0.01........................
[CV 1/5; 8/9] END dropout_rate=0.2, learning_rate=0.01;, score=nan total time=   4.1s
[CV 2/5; 8/9] START dropout_rate=0.2, learning_rate=0.01........................
[CV 2/5; 8/9] END dropout_rate=0.2, learning_rate=0.01;, score=nan total time=   3.7s
[CV 3/5; 8/9] START dropout_rate=0.2, learning_rate=0.01........................
[CV 3/5; 8/9] END dropout_rate=0.2, learning_rate=0.01;, score=nan total time=   5.9s
[CV 4/5; 8/9] START dropout_rate=0.2, learning_rate=0.01........................
[CV 4/5; 8/9] END dropout_rate=0.2, learning_rate=0.01;, score=nan total time=   5.8s
[CV 5/5; 8/9] START dropout_rate=0.2, learning_rate=0.01........................
[CV 5/5; 8/9] END dropout_rate=0.2, learning_rate=0.01;, score=nan total time=   3.6s
[CV 1/5; 9/9] START dropout_rate=0.2, learning_rate=0.1.........................
[CV 1/5; 9/9] END dropout_rate=0.2, learning_rate=0.1;, score=nan total time=   5.8s
[CV 2/5; 9/9] START dropout_rate=0.2, learning_rate=0.1.........................
[CV 2/5; 9/9] END dropout_rate=0.2, learning_rate=0.1;, score=nan total time=   5.8s
[CV 3/5; 9/9] START dropout_rate=0.2, learning_rate=0.1.........................
[CV 3/5; 9/9] END dropout_rate=0.2, learning_rate=0.1;, score=nan total time=   5.8s
[CV 4/5; 9/9] START dropout_rate=0.2, learning_rate=0.1.........................
[CV 4/5; 9/9] END dropout_rate=0.2, learning_rate=0.1;, score=nan total time=   4.4s
[CV 5/5; 9/9] START dropout_rate=0.2, learning_rate=0.1.........................
[CV 5/5; 9/9] END dropout_rate=0.2, learning_rate=0.1;, score=nan total time=   4.2s

In [25]:
print('Best : {}, using {}'.format(grid_result.best_score_,grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
  print('{},{} with: {}'.format(mean, stdev, param))

Best : nan, using {'dropout_rate': 0.0, 'learning_rate': 0.001}
nan,nan with: {'dropout_rate': 0.0, 'learning_rate': 0.001}
nan,nan with: {'dropout_rate': 0.0, 'learning_rate': 0.01}
nan,nan with: {'dropout_rate': 0.0, 'learning_rate': 0.1}
nan,nan with: {'dropout_rate': 0.1, 'learning_rate': 0.001}
nan,nan with: {'dropout_rate': 0.1, 'learning_rate': 0.01}
nan,nan with: {'dropout_rate': 0.1, 'learning_rate': 0.1}
nan,nan with: {'dropout_rate': 0.2, 'learning_rate': 0.001}
nan,nan with: {'dropout_rate': 0.2, 'learning_rate': 0.01}
nan,nan with: {'dropout_rate': 0.2, 'learning_rate': 0.1}

In [26]:
def create_model(activation_function,init):
    model = Sequential()
    model.add(Dense(8,input_dim = 3,kernel_initializer = init,activation = activation_function))
    model.add(Dropout(0.1))
    model.add(Dense(4,input_dim = 3,kernel_initializer = init,activation = activation_function))
    model.add(Dropout(0.1))
    model.add(Dense(1,activation = 'sigmoid'))
    
    adam = Adam(lr = 0.001)
    model.compile(loss = 'mse',optimizer = adam,metrics = ['mse'])
    return model

In [27]:
model = KerasClassifier(build_fn = create_model,verbose = 0,batch_size = 40,epochs = 10)

# Define the grid search parameters
activation_function = ['softmax','relu','tanh','linear']
init = ['uniform','normal','zero']

# Make a dictionary of the grid search parameters
param_grids = dict(activation_function = activation_function,init = init)

# Build and fit the GridSearchCV

grid = GridSearchCV(estimator = model,param_grid = param_grids,cv = KFold(),verbose = 10)
grid_result = grid.fit(X_standardized,y)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5; 1/12] START activation_function=softmax, init=uniform..................
[CV 1/5; 1/12] END activation_function=softmax, init=uniform;, score=nan total time=   3.9s
[CV 2/5; 1/12] START activation_function=softmax, init=uniform..................
[CV 2/5; 1/12] END activation_function=softmax, init=uniform;, score=nan total time=   5.9s
[CV 3/5; 1/12] START activation_function=softmax, init=uniform..................
[CV 3/5; 1/12] END activation_function=softmax, init=uniform;, score=nan total time=   3.8s
[CV 4/5; 1/12] START activation_function=softmax, init=uniform..................
[CV 4/5; 1/12] END activation_function=softmax, init=uniform;, score=nan total time=   5.9s
[CV 5/5; 1/12] START activation_function=softmax, init=uniform..................
[CV 5/5; 1/12] END activation_function=softmax, init=uniform;, score=nan total time=   5.8s
[CV 1/5; 2/12] START activation_function=softmax, init=normal...................
[CV 1/5; 2/12] END activation_function=softmax, init=normal;, score=nan total time=   5.8s
[CV 2/5; 2/12] START activation_function=softmax, init=normal...................
[CV 2/5; 2/12] END activation_function=softmax, init=normal;, score=nan total time=   3.7s
[CV 3/5; 2/12] START activation_function=softmax, init=normal...................
[CV 3/5; 2/12] END activation_function=softmax, init=normal;, score=nan total time=   3.7s
[CV 4/5; 2/12] START activation_function=softmax, init=normal...................
[CV 4/5; 2/12] END activation_function=softmax, init=normal;, score=nan total time=   5.9s
[CV 5/5; 2/12] START activation_function=softmax, init=normal...................
[CV 5/5; 2/12] END activation_function=softmax, init=normal;, score=nan total time=   5.8s
[CV 1/5; 3/12] START activation_function=softmax, init=zero.....................
[CV 1/5; 3/12] END activation_function=softmax, init=zero;, score=nan total time=   4.0s
[CV 2/5; 3/12] START activation_function=softmax, init=zero.....................
[CV 2/5; 3/12] END activation_function=softmax, init=zero;, score=nan total time=   5.8s
[CV 3/5; 3/12] START activation_function=softmax, init=zero.....................
[CV 3/5; 3/12] END activation_function=softmax, init=zero;, score=nan total time=   5.9s
[CV 4/5; 3/12] START activation_function=softmax, init=zero.....................
[CV 4/5; 3/12] END activation_function=softmax, init=zero;, score=nan total time=   4.5s
[CV 5/5; 3/12] START activation_function=softmax, init=zero.....................
[CV 5/5; 3/12] END activation_function=softmax, init=zero;, score=nan total time=   4.0s
[CV 1/5; 4/12] START activation_function=relu, init=uniform.....................
[CV 1/5; 4/12] END activation_function=relu, init=uniform;, score=nan total time=   4.2s
[CV 2/5; 4/12] START activation_function=relu, init=uniform.....................
[CV 2/5; 4/12] END activation_function=relu, init=uniform;, score=nan total time=   6.0s
[CV 3/5; 4/12] START activation_function=relu, init=uniform.....................
[CV 3/5; 4/12] END activation_function=relu, init=uniform;, score=nan total time=   5.8s
[CV 4/5; 4/12] START activation_function=relu, init=uniform.....................
[CV 4/5; 4/12] END activation_function=relu, init=uniform;, score=nan total time=   3.7s
[CV 5/5; 4/12] START activation_function=relu, init=uniform.....................
[CV 5/5; 4/12] END activation_function=relu, init=uniform;, score=nan total time=   5.8s
[CV 1/5; 5/12] START activation_function=relu, init=normal......................
[CV 1/5; 5/12] END activation_function=relu, init=normal;, score=nan total time=   3.6s
[CV 2/5; 5/12] START activation_function=relu, init=normal......................
[CV 2/5; 5/12] END activation_function=relu, init=normal;, score=nan total time=   3.7s
[CV 3/5; 5/12] START activation_function=relu, init=normal......................
[CV 3/5; 5/12] END activation_function=relu, init=normal;, score=nan total time=   4.0s
[CV 4/5; 5/12] START activation_function=relu, init=normal......................
[CV 4/5; 5/12] END activation_function=relu, init=normal;, score=nan total time=   3.7s
[CV 5/5; 5/12] START activation_function=relu, init=normal......................
[CV 5/5; 5/12] END activation_function=relu, init=normal;, score=nan total time=   3.7s
[CV 1/5; 6/12] START activation_function=relu, init=zero........................
[CV 1/5; 6/12] END activation_function=relu, init=zero;, score=nan total time=   5.8s
[CV 2/5; 6/12] START activation_function=relu, init=zero........................
[CV 2/5; 6/12] END activation_function=relu, init=zero;, score=nan total time=   5.9s
[CV 3/5; 6/12] START activation_function=relu, init=zero........................
[CV 3/5; 6/12] END activation_function=relu, init=zero;, score=nan total time=   5.8s
[CV 4/5; 6/12] START activation_function=relu, init=zero........................
[CV 4/5; 6/12] END activation_function=relu, init=zero;, score=nan total time=   3.5s
[CV 5/5; 6/12] START activation_function=relu, init=zero........................
[CV 5/5; 6/12] END activation_function=relu, init=zero;, score=nan total time=   6.5s
[CV 1/5; 7/12] START activation_function=tanh, init=uniform.....................
[CV 1/5; 7/12] END activation_function=tanh, init=uniform;, score=nan total time=   5.9s
[CV 2/5; 7/12] START activation_function=tanh, init=uniform.....................
[CV 2/5; 7/12] END activation_function=tanh, init=uniform;, score=nan total time=   5.8s
[CV 3/5; 7/12] START activation_function=tanh, init=uniform.....................
[CV 3/5; 7/12] END activation_function=tanh, init=uniform;, score=nan total time=   3.8s
[CV 4/5; 7/12] START activation_function=tanh, init=uniform.....................
[CV 4/5; 7/12] END activation_function=tanh, init=uniform;, score=nan total time=   6.0s
[CV 5/5; 7/12] START activation_function=tanh, init=uniform.....................
[CV 5/5; 7/12] END activation_function=tanh, init=uniform;, score=nan total time=   3.6s
[CV 1/5; 8/12] START activation_function=tanh, init=normal......................
[CV 1/5; 8/12] END activation_function=tanh, init=normal;, score=nan total time=   5.8s
[CV 2/5; 8/12] START activation_function=tanh, init=normal......................
[CV 2/5; 8/12] END activation_function=tanh, init=normal;, score=nan total time=   4.0s
[CV 3/5; 8/12] START activation_function=tanh, init=normal......................
[CV 3/5; 8/12] END activation_function=tanh, init=normal;, score=nan total time=   3.7s
[CV 4/5; 8/12] START activation_function=tanh, init=normal......................
[CV 4/5; 8/12] END activation_function=tanh, init=normal;, score=nan total time=   5.9s
[CV 5/5; 8/12] START activation_function=tanh, init=normal......................
[CV 5/5; 8/12] END activation_function=tanh, init=normal;, score=nan total time=   3.6s
[CV 1/5; 9/12] START activation_function=tanh, init=zero........................
[CV 1/5; 9/12] END activation_function=tanh, init=zero;, score=nan total time=   5.8s
[CV 2/5; 9/12] START activation_function=tanh, init=zero........................
[CV 2/5; 9/12] END activation_function=tanh, init=zero;, score=nan total time=   5.8s
[CV 3/5; 9/12] START activation_function=tanh, init=zero........................
[CV 3/5; 9/12] END activation_function=tanh, init=zero;, score=nan total time=   5.9s
[CV 4/5; 9/12] START activation_function=tanh, init=zero........................
[CV 4/5; 9/12] END activation_function=tanh, init=zero;, score=nan total time=   5.8s
[CV 5/5; 9/12] START activation_function=tanh, init=zero........................
[CV 5/5; 9/12] END activation_function=tanh, init=zero;, score=nan total time=   3.7s
[CV 1/5; 10/12] START activation_function=linear, init=uniform..................
[CV 1/5; 10/12] END activation_function=linear, init=uniform;, score=nan total time=   5.8s
[CV 2/5; 10/12] START activation_function=linear, init=uniform..................
[CV 2/5; 10/12] END activation_function=linear, init=uniform;, score=nan total time=   4.6s
[CV 3/5; 10/12] START activation_function=linear, init=uniform..................
[CV 3/5; 10/12] END activation_function=linear, init=uniform;, score=nan total time=   5.9s
[CV 4/5; 10/12] START activation_function=linear, init=uniform..................
[CV 4/5; 10/12] END activation_function=linear, init=uniform;, score=nan total time=   3.6s
[CV 5/5; 10/12] START activation_function=linear, init=uniform..................
[CV 5/5; 10/12] END activation_function=linear, init=uniform;, score=nan total time=   3.5s
[CV 1/5; 11/12] START activation_function=linear, init=normal...................
[CV 1/5; 11/12] END activation_function=linear, init=normal;, score=nan total time=   4.0s
[CV 2/5; 11/12] START activation_function=linear, init=normal...................
[CV 2/5; 11/12] END activation_function=linear, init=normal;, score=nan total time=   3.6s
[CV 3/5; 11/12] START activation_function=linear, init=normal...................
[CV 3/5; 11/12] END activation_function=linear, init=normal;, score=nan total time=   5.9s
[CV 4/5; 11/12] START activation_function=linear, init=normal...................
[CV 4/5; 11/12] END activation_function=linear, init=normal;, score=nan total time=   5.9s
[CV 5/5; 11/12] START activation_function=linear, init=normal...................
[CV 5/5; 11/12] END activation_function=linear, init=normal;, score=nan total time=   5.8s
[CV 1/5; 12/12] START activation_function=linear, init=zero.....................
[CV 1/5; 12/12] END activation_function=linear, init=zero;, score=nan total time=   4.0s
[CV 2/5; 12/12] START activation_function=linear, init=zero.....................
[CV 2/5; 12/12] END activation_function=linear, init=zero;, score=nan total time=   5.9s
[CV 3/5; 12/12] START activation_function=linear, init=zero.....................
[CV 3/5; 12/12] END activation_function=linear, init=zero;, score=nan total time=   5.8s
[CV 4/5; 12/12] START activation_function=linear, init=zero.....................
[CV 4/5; 12/12] END activation_function=linear, init=zero;, score=nan total time=   3.8s
[CV 5/5; 12/12] START activation_function=linear, init=zero.....................
[CV 5/5; 12/12] END activation_function=linear, init=zero;, score=nan total time=   5.8s

In [28]:
print('Best : {}, using {}'.format(grid_result.best_score_,grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
  print('{},{} with: {}'.format(mean, stdev, param))

Best : nan, using {'activation_function': 'softmax', 'init': 'uniform'}
nan,nan with: {'activation_function': 'softmax', 'init': 'uniform'}
nan,nan with: {'activation_function': 'softmax', 'init': 'normal'}
nan,nan with: {'activation_function': 'softmax', 'init': 'zero'}
nan,nan with: {'activation_function': 'relu', 'init': 'uniform'}
nan,nan with: {'activation_function': 'relu', 'init': 'normal'}
nan,nan with: {'activation_function': 'relu', 'init': 'zero'}
nan,nan with: {'activation_function': 'tanh', 'init': 'uniform'}
nan,nan with: {'activation_function': 'tanh', 'init': 'normal'}
nan,nan with: {'activation_function': 'tanh', 'init': 'zero'}
nan,nan with: {'activation_function': 'linear', 'init': 'uniform'}
nan,nan with: {'activation_function': 'linear', 'init': 'normal'}
nan,nan with: {'activation_function': 'linear', 'init': 'zero'}

In [29]:
def create_model(neuron1,neuron2):
    model = Sequential()
    model.add(Dense(neuron1,input_dim = 3,kernel_initializer = 'uniform',activation = 'tanh'))
    model.add(Dropout(0.2))
    model.add(Dense(neuron2,input_dim = neuron1,kernel_initializer = 'uniform',activation = 'tanh'))
    model.add(Dropout(0.1))
    model.add(Dense(1,activation = 'sigmoid'))
    
    adam = Adam(lr = 0.001)
    model.compile(loss = 'mse',optimizer = adam,metrics = ['mse'])
    return model

In [30]:
model = KerasClassifier(build_fn = create_model,verbose = 0,batch_size = 40,epochs = 10)

# Define the grid search parameters

neuron1 = [4,8,16]
neuron2 = [2,4,8]

# Make a dictionary of the grid search parameters

param_grids = dict(neuron1 = neuron1,neuron2 = neuron2)

# Build and fit the GridSearchCV

grid = GridSearchCV(estimator = model,param_grid = param_grids,cv = KFold(),verbose = 10)
grid_result = grid.fit(X_standardized,y)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV 1/5; 1/9] START neuron1=4, neuron2=2........................................
[CV 1/5; 1/9] END ...........neuron1=4, neuron2=2;, score=nan total time=   5.9s
[CV 2/5; 1/9] START neuron1=4, neuron2=2........................................
[CV 2/5; 1/9] END ...........neuron1=4, neuron2=2;, score=nan total time=   6.7s
[CV 3/5; 1/9] START neuron1=4, neuron2=2........................................
[CV 3/5; 1/9] END ...........neuron1=4, neuron2=2;, score=nan total time=   3.9s
[CV 4/5; 1/9] START neuron1=4, neuron2=2........................................
[CV 4/5; 1/9] END ...........neuron1=4, neuron2=2;, score=nan total time=   4.2s
[CV 5/5; 1/9] START neuron1=4, neuron2=2........................................
[CV 5/5; 1/9] END ...........neuron1=4, neuron2=2;, score=nan total time=   5.9s
[CV 1/5; 2/9] START neuron1=4, neuron2=4........................................
[CV 1/5; 2/9] END ...........neuron1=4, neuron2=4;, score=nan total time=   5.8s
[CV 2/5; 2/9] START neuron1=4, neuron2=4........................................
[CV 2/5; 2/9] END ...........neuron1=4, neuron2=4;, score=nan total time=   5.9s
[CV 3/5; 2/9] START neuron1=4, neuron2=4........................................
[CV 3/5; 2/9] END ...........neuron1=4, neuron2=4;, score=nan total time=   5.8s
[CV 4/5; 2/9] START neuron1=4, neuron2=4........................................
[CV 4/5; 2/9] END ...........neuron1=4, neuron2=4;, score=nan total time=   5.9s
[CV 5/5; 2/9] START neuron1=4, neuron2=4........................................
[CV 5/5; 2/9] END ...........neuron1=4, neuron2=4;, score=nan total time=   4.1s
[CV 1/5; 3/9] START neuron1=4, neuron2=8........................................
[CV 1/5; 3/9] END ...........neuron1=4, neuron2=8;, score=nan total time=   5.8s
[CV 2/5; 3/9] START neuron1=4, neuron2=8........................................
[CV 2/5; 3/9] END ...........neuron1=4, neuron2=8;, score=nan total time=   3.7s
[CV 3/5; 3/9] START neuron1=4, neuron2=8........................................
[CV 3/5; 3/9] END ...........neuron1=4, neuron2=8;, score=nan total time=   4.0s
[CV 4/5; 3/9] START neuron1=4, neuron2=8........................................
[CV 4/5; 3/9] END ...........neuron1=4, neuron2=8;, score=nan total time=   5.9s
[CV 5/5; 3/9] START neuron1=4, neuron2=8........................................
[CV 5/5; 3/9] END ...........neuron1=4, neuron2=8;, score=nan total time=   4.0s
[CV 1/5; 4/9] START neuron1=8, neuron2=2........................................
[CV 1/5; 4/9] END ...........neuron1=8, neuron2=2;, score=nan total time=   5.8s
[CV 2/5; 4/9] START neuron1=8, neuron2=2........................................
[CV 2/5; 4/9] END ...........neuron1=8, neuron2=2;, score=nan total time=   3.7s
[CV 3/5; 4/9] START neuron1=8, neuron2=2........................................
[CV 3/5; 4/9] END ...........neuron1=8, neuron2=2;, score=nan total time=   5.9s
[CV 4/5; 4/9] START neuron1=8, neuron2=2........................................
[CV 4/5; 4/9] END ...........neuron1=8, neuron2=2;, score=nan total time=   3.6s
[CV 5/5; 4/9] START neuron1=8, neuron2=2........................................
[CV 5/5; 4/9] END ...........neuron1=8, neuron2=2;, score=nan total time=   5.1s
[CV 1/5; 5/9] START neuron1=8, neuron2=4........................................
[CV 1/5; 5/9] END ...........neuron1=8, neuron2=4;, score=nan total time=   3.8s
[CV 2/5; 5/9] START neuron1=8, neuron2=4........................................
[CV 2/5; 5/9] END ...........neuron1=8, neuron2=4;, score=nan total time=   3.8s
[CV 3/5; 5/9] START neuron1=8, neuron2=4........................................
[CV 3/5; 5/9] END ...........neuron1=8, neuron2=4;, score=nan total time=   4.0s
[CV 4/5; 5/9] START neuron1=8, neuron2=4........................................
[CV 4/5; 5/9] END ...........neuron1=8, neuron2=4;, score=nan total time=   3.6s
[CV 5/5; 5/9] START neuron1=8, neuron2=4........................................
[CV 5/5; 5/9] END ...........neuron1=8, neuron2=4;, score=nan total time=   3.6s
[CV 1/5; 6/9] START neuron1=8, neuron2=8........................................
[CV 1/5; 6/9] END ...........neuron1=8, neuron2=8;, score=nan total time=   5.8s
[CV 2/5; 6/9] START neuron1=8, neuron2=8........................................
[CV 2/5; 6/9] END ...........neuron1=8, neuron2=8;, score=nan total time=   3.6s
[CV 3/5; 6/9] START neuron1=8, neuron2=8........................................
[CV 3/5; 6/9] END ...........neuron1=8, neuron2=8;, score=nan total time=   3.5s
[CV 4/5; 6/9] START neuron1=8, neuron2=8........................................
[CV 4/5; 6/9] END ...........neuron1=8, neuron2=8;, score=nan total time=   5.8s
[CV 5/5; 6/9] START neuron1=8, neuron2=8........................................
[CV 5/5; 6/9] END ...........neuron1=8, neuron2=8;, score=nan total time=   5.8s
[CV 1/5; 7/9] START neuron1=16, neuron2=2.......................................
[CV 1/5; 7/9] END ..........neuron1=16, neuron2=2;, score=nan total time=   5.9s
[CV 2/5; 7/9] START neuron1=16, neuron2=2.......................................
[CV 2/5; 7/9] END ..........neuron1=16, neuron2=2;, score=nan total time=   3.6s
[CV 3/5; 7/9] START neuron1=16, neuron2=2.......................................
[CV 3/5; 7/9] END ..........neuron1=16, neuron2=2;, score=nan total time=   5.8s
[CV 4/5; 7/9] START neuron1=16, neuron2=2.......................................
[CV 4/5; 7/9] END ..........neuron1=16, neuron2=2;, score=nan total time=   3.7s
[CV 5/5; 7/9] START neuron1=16, neuron2=2.......................................
[CV 5/5; 7/9] END ..........neuron1=16, neuron2=2;, score=nan total time=   3.6s
[CV 1/5; 8/9] START neuron1=16, neuron2=4.......................................
[CV 1/5; 8/9] END ..........neuron1=16, neuron2=4;, score=nan total time=   4.1s
[CV 2/5; 8/9] START neuron1=16, neuron2=4.......................................
[CV 2/5; 8/9] END ..........neuron1=16, neuron2=4;, score=nan total time=   6.7s
[CV 3/5; 8/9] START neuron1=16, neuron2=4.......................................
[CV 3/5; 8/9] END ..........neuron1=16, neuron2=4;, score=nan total time=   5.9s
[CV 4/5; 8/9] START neuron1=16, neuron2=4.......................................
[CV 4/5; 8/9] END ..........neuron1=16, neuron2=4;, score=nan total time=   5.9s
[CV 5/5; 8/9] START neuron1=16, neuron2=4.......................................
[CV 5/5; 8/9] END ..........neuron1=16, neuron2=4;, score=nan total time=   5.8s
[CV 1/5; 9/9] START neuron1=16, neuron2=8.......................................
[CV 1/5; 9/9] END ..........neuron1=16, neuron2=8;, score=nan total time=   5.9s
[CV 2/5; 9/9] START neuron1=16, neuron2=8.......................................
[CV 2/5; 9/9] END ..........neuron1=16, neuron2=8;, score=nan total time=   5.8s
[CV 3/5; 9/9] START neuron1=16, neuron2=8.......................................
[CV 3/5; 9/9] END ..........neuron1=16, neuron2=8;, score=nan total time=   5.8s
[CV 4/5; 9/9] START neuron1=16, neuron2=8.......................................
[CV 4/5; 9/9] END ..........neuron1=16, neuron2=8;, score=nan total time=   5.8s
[CV 5/5; 9/9] START neuron1=16, neuron2=8.......................................
[CV 5/5; 9/9] END ..........neuron1=16, neuron2=8;, score=nan total time=   5.9s

In [31]:
print('Best : {}, using {}'.format(grid_result.best_score_,grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
  print('{},{} with: {}'.format(mean, stdev, param))

Best : nan, using {'neuron1': 4, 'neuron2': 2}
nan,nan with: {'neuron1': 4, 'neuron2': 2}
nan,nan with: {'neuron1': 4, 'neuron2': 4}
nan,nan with: {'neuron1': 4, 'neuron2': 8}
nan,nan with: {'neuron1': 8, 'neuron2': 2}
nan,nan with: {'neuron1': 8, 'neuron2': 4}
nan,nan with: {'neuron1': 8, 'neuron2': 8}
nan,nan with: {'neuron1': 16, 'neuron2': 2}
nan,nan with: {'neuron1': 16, 'neuron2': 4}
nan,nan with: {'neuron1': 16, 'neuron2': 8}

In [32]:
from sklearn.metrics import classification_report, accuracy_score
def create_model():
    model = Sequential()
    model.add(Dense(16,input_dim = 3,kernel_initializer = 'normal',activation = 'linear'))
    model.add(Dropout(0.1))
    model.add(Dense(8,input_dim = 3,kernel_initializer = 'normal',activation = 'linear'))
    model.add(Dropout(0.1))
    model.add(Dense(1,activation = 'linear'))
    
    adam = Adam(lr = 0.01) #sgd = SGD(lr=learning_rate, momentum=momentum, decay=decay_rate, nesterov=False)
    model.compile(loss = 'mse',optimizer = adam,metrics = ['mse'])
    return model

In [33]:
model = KerasClassifier(build_fn = create_model,verbose = 0,batch_size = 40,epochs = 100)

# Fitting the model

model.fit(X_standardized,y)

# Predicting using trained model

y_predict = model.predict(X_standardized)

# Printing the metrics
print(accuracy_score(y_predict.round(),y.round()))

470/470 [==============================] - 1s 923us/step
0.0016623445707826317